<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Mercurio.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="4.5.0" />
        <PackageReference Include="Testcontainers.RabbitMq" Version="4.11.0" />
    </ItemGroup>

</Project>
