// -------------------------------------------------------------------------------------------------
//  <copyright file="DefaultExchangeConfiguration.cs" company="Starion Group S.A.">
// 
//    Copyright 2025 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace Mercurio.Model
{
    /// <summary>
    /// The <see cref="DefaultExchangeConfiguration" /> is simplified <see cref="DirectExchangeConfiguration" /> that used the default exchange, pre-declared by the server
    /// </summary>
    public class DefaultExchangeConfiguration : DirectExchangeConfiguration
    {
        /// <summary>
        /// Initializes a new instance of <see cref="DefaultExchangeConfiguration" />
        /// </summary>
        /// <param name="queueName">The name of the queue to be created or used. Default value is _string.empty_. In case of empty, the queue name is generated by the server</param>
        /// <param name="isTemporary">
        /// Asserts that the queue should be a temporary one or not. In case of a temporary queue, the queue is automatically deleted when the consumer
        /// of the queue disconnects.
        /// </param>
        public DefaultExchangeConfiguration(string queueName = "", bool isTemporary = false) : base(queueName, "", isTemporary: isTemporary)
        {
        }
    }
}
